spring.application.name=projeto

spring.datasource.url=jdbc:postgresql://${HOST}:${PORT}/${DATABASE}
spring.datasource.username=${USUARIO_DB}
spring.datasource.password=${SENHA_DB}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.app.jwtExpirationMs=${TEMPO_EM_MILISEGUNDOS}
spring.app.jwtSecret=${SENHA_JWT}
spring.app.jwtCookie=${COOKIE_JWT}

logging.level.org.springframework.security=DEBUG
logging.level.com.inventario.projeto=DEBUG
logging.level.org.hibernate.SQL=DEBUG